version: '3'
services:
  pgdatabase:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - ./ny_taxi_postgres_data/:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - pg-database

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - ./pg_admin_con:/var/lib/pgadmin/data
    ports:
      - 5050:80

networks:
  pg-database:
    name: 2_docker_sql_default
    external: true
