bq-dbt-workshop:
  outputs:
    dev:
      dataset: trips_all_data
      fixed_retries: 1
      keyfile: /.google/credentials/google_credentials_2024.json
      location: asia-south1
      method: service-account
      priority: interactive
      project: de-zoomcamp-413815
      threads: 4
      timeout_seconds: 300
      type: bigquery
  target: dev
taxi_rides_ny:
  outputs:
    dev:
      dataset: ny_taxi
      fixed_retries: 1
      location: EU
      method: oauth
      priority: interactive
      project: de-zoomcamp-413815
      threads: 3
      timeout_seconds: 300
      type: bigquery
  target: dev
